### ISSUE TITLE
Define the agent to call the server

### ISSUE THREAD

**Issue by phoenix741** [foxglove/xmlrpc#16]
I would like to define the agent used by the methodCall (via fetch) to define a company proxy (like hpagent).

How can i define this agent ?

Thanks

**Comment by jhurliman** [comment]
The HTTP(S) client is not currently pluggable like the HTTP(S) server in this library, it will always use `fetch()` either directly from the browser or from the node-fetch library in node.js. The best way to change this behavior for now is to subclass the XmlRpcClient class and override `methodCall()` with your own implementation. Another option would be to refactor the library to define an interface for HTTP fetching and have XmlRpcClient optionally accept a function that does the fetch and returns a promise. I don't have bandwidth to work on this modification myself but am happy to review pull requests if you want to tackle it.
